Capture result and exit code from shasum command.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -80,7 +80,12 @@ jobs:
             VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
             for i in 1 256 512
             do
-              shasum -a $i -c <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM) || { echo "Codecov failed SHA$i check"; exit 0; }
+              result=$(shasum -a $i -c <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM) 2>&1)
+              exit=$?
+              if [ $exit -ne 0 ]; then
+               echo "Codecov failed SHA$i check; $result"
+               exit 0
+              fi
             done
             bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPEdge" -t ${CODECOV_TOKEN}
 
