Fix format of circleci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -77,13 +77,13 @@ jobs:
       - run:
           name: Upload Code Coverage Report
           command: |
-          curl -s https://codecov.io/bash > codecov1;
-          VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
-          for i in 1 256 512
-          do
-            shasum -a $i -c <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM) || { echo "Codecov failed SHA$i check"; exit 0; }
-          done
-          bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPEdge" -t ${CODECOV_TOKEN}
+            curl -s https://codecov.io/bash > codecov1;
+            VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
+            for i in 1 256 512
+            do
+              shasum -a $i -c <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM) || { echo "Codecov failed SHA$i check"; exit 0; }
+            done
+            bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPEdge" -t ${CODECOV_TOKEN}
 
       # verify XCFramework archive builds
       - run:
