Add on-failure error handling step and dynamic step naming
Use simulated test failure to test error handling

diff --git a/.github/workflows/upstream-integration-test.yml b/.github/workflows/upstream-integration-test.yml
--- a/.github/workflows/upstream-integration-test.yml
+++ b/.github/workflows/upstream-integration-test.yml
@@ -54,6 +54,7 @@ jobs:
     steps:
 
     - name: Job run identifier ${{ github.event.inputs.id }}
+      id: job-run-identifier
       run: |
         if [ -z "${{ github.event.inputs.id }}" ]; then \
           echo No job run identifier was set.
@@ -62,11 +63,13 @@ jobs:
         fi;
 
     - name: Checkout
+      id: checkout
       uses: actions/checkout@v3
       with:
         ref: ${{ github.event.inputs.branch }}
 
     - name: Cache Cocoapods
+      id: cache-cocoapods
       uses: actions/cache@v3
       with:
         path: Pods
@@ -76,10 +79,54 @@ jobs:
 
     # Runs a single command using the runners shell
     - name: Execute Edge Network integration tests
+      id: execute-integration-tests
       run: make test-integration-upstream EDGE_ENVIRONMENT=${{ github.event.inputs.environment }} EDGE_LOCATION_HINT=${{ github.event.inputs.edge-location-hint }}
-    
+
+    # TEST ONLY - DELETE BEFORE MERGING
+    - name: Simulate workflow failure
+      id: simulate-failure
+      run: exit 2
+
     # Potential workflow solutions on job failure
+    # All workflow setup step failures give exit code 2, with 3 as fallback
+    # Actual integration test failures give exit code 1
     - name: On failure
+      id: on-failure
+      if: ${{ failure() }}
+      run: |
+        echo 'Job used branch:  ${{ github.event.inputs.branch }}. Please make sure this is the branch to run off of.'
+        
+        : # Initialize default exit code
+        EXIT_CODE=3
+
+        if [[ "${{ steps.job-run-identifier.conclusion }}" == "failure" ]]; then
+          echo "Job step failed: Job run identifier."
+          EXIT_CODE=2
+        elif [[ "${{ steps.checkout.conclusion }}" == "failure" ]]; then
+          echo "Job step failed: Checkout."
+          EXIT_CODE=2
+        elif [[ "${{ steps.cache-cocoapods.conclusion }}" == "failure" ]]; then
+          echo "Job step failed: Cache Cocoapods."
+          EXIT_CODE=2
+        elif [[ "${{ steps.simulate-failure.conclusion }}" == "failure" ]]; then
+          echo "Job step failed: Simulate failure."
+          EXIT_CODE=2
+        elif [[ "${{ steps.execute-integration-tests.conclusion }}" == "failure" ]]; then
+          echo "Job step failed: Execute Edge Network integration tests."
+          EXIT_CODE=1
+        else
+          echo "Job failed: Failure cause not identified."
+          : # EXIT_CODE remains as the default value 3
+        fi
+
+        : # Echo the exit code to the GITHUB_ENV file, making it available to subsequent steps
+        echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
+
+    - name: "${{ toJson(steps.on-failure.outputs.EXIT_CODE) }}"
+      id: failure-data
       if: ${{ failure() }}
       run: |
         echo 'Job used branch: ' ${{ github.event.inputs.branch }}. Please make sure this is the branch to run off of.
+        
+    
+
